version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'electron'
        update-types: ['version-update:semver-major']
