critical:
  - '(critical|urgent)'

windows:
  - '(windows|Windows)'

macos:
  - '(mac|Mac)'
  - '(macos|MacOS|macOS)'

linux:
  - '(linux|Linux)'
  - '(ubuntu|Ubuntu)'
  - '(fedora|Fedora)'

bug:
  - bug

documentation:
  - docs
  - document
  - documentation
  - '(readme|README)'

security:
  - security
