name: Build
on:
  workflow_call:

jobs:
  build-win:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Build
        run: yarn dist:win
      - name: Upload
        run: |
          version="$(git describe --abbrev=0 --tags)"
          gh release upload $version "dist/hider-$version-win-x64.exe" "dist/hider-$version-win-ia32.exe" "dist/latest.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    name: Build (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Build
        run: yarn dist:mac
      - name: Upload
        run: |
          version="$(git describe --abbrev=0 --tags)"
          gh release upload $version "dist/hider-$version-mac-x64.dmg" "dist/hider-$version-mac-arm64.dmg" "dist/latest-mac.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Build
        run: yarn dist:linux
      - name: Upload
        run: |
          version="$(git describe --abbrev=0 --tags)"
          gh release upload $version "dist/hider-$version-linux-x64.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
