name: CI

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn webpack
      - run: yarn dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn dist:mac-arm64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create CHANGELOG.md
        id: set_changelog
        run: |
          echo -e "# ${{ steps.get_version.outputs.VERSION }} ($(date +'%Y-%m-%d'))" > CHANGELOG.md
          echo "::set-output name=changelog::$(cat CHANGELOG.md)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Hider ${{ github.ref }}
          body: ${{ steps.set_changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './dist/hider-${{ steps.get_version.outputs.VERSION }}-win-x64.exe'
          asset_name: 'Hider-${{ steps.get_version.outputs.VERSION }}-win-x64.exe'
          asset_content_type: application/exe

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './dist/hider-${{ steps.get_version.outputs.VERSION }}-linux-x64.zip'
          asset_name: 'hider-${{ steps.get_version.outputs.VERSION }}-linux-x64.zip'
          asset_content_type: application/zip

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './dist/hider-${{ steps.get_version.outputs.VERSION }}-mac-x64.dmg'
          asset_name: 'hider-${{ steps.get_version.outputs.VERSION }}-mac-x64.dmg'
          asset_content_type: application/dmg

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './dist/hider-${{ steps.get_version.outputs.VERSION }}-mac-arm64.dmg'
          asset_name: 'hider-${{ steps.get_version.outputs.VERSION }}-mac-arm64.dmg'
          asset_content_type: application/dmg
