name: CI

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Run shell command
        run: ./.github/scripts/ci.sh
        shell: bash
