name: Release (npm)
on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: 'yarn'
          registry-url: https://npm.pkg.github.com/

      - run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Publish (Core)
        run: yarn workspace @cjeonguk/hider publish
      - name: Publish (CLI)
        run: yarn workspace @cjeonguk/hider-cli publish
